from importlib import import_module
from typing import Any

from agenomic.knowledge.models import (
    UNSET,
    ActorRef,
    AgentBindingResult,
    AgentKnowledge,
    AgentKnowledgeBinding,
    AgentKnowledgeConfig,
    AgentKnowledgeManifest,
    AgentKnowledgeRelease,
    AgentSearchResponse,
    AnswerResponse,
    Backlink,
    BacklinkList,
    Citation,
    DocumentDetail,
    DocumentList,
    DocumentRevision,
    DocumentText,
    DocumentWrite,
    EvidenceConflict,
    ExecutionPin,
    FolderNode,
    KnowledgeBaseDetail,
    KnowledgeBaseHealth,
    KnowledgeBaseRecord,
    KnowledgeBaseStats,
    KnowledgeCollection,
    KnowledgeDiff,
    KnowledgeDocument,
    KnowledgeJob,
    KnowledgeRefs,
    KnowledgeSection,
    KnowledgeVersion,
    Publication,
    PublicationEvent,
    QueryResponse,
    RetrievalEvent,
    RetrievalInfo,
    RetrievalSnapshot,
    RevisionList,
    RiskAssessment,
    SearchResponse,
    SearchResult,
    SectionDetail,
    SectionMatch,
    SectionTree,
    Unset,
    VersionDecision,
    VersionDetail,
    VersionLike,
    VersionSelector,
    VersionVerification,
    VersionWrite,
    normalize_version,
    version_number,
)
from agenomic.knowledge.resources import (
    AgentKnowledgeResource,
    KnowledgeBase,
    KnowledgeCollectionsResource,
    KnowledgeDocumentsResource,
    KnowledgeJobsResource,
    KnowledgeResource,
    KnowledgeRetrievalsResource,
    KnowledgeVersionsResource,
)
from agenomic.knowledge.tools import knowledge_tool

__all__ = [
    "UNSET",
    "ActorRef",
    "AgentBindingResult",
    "AgentKnowledge",
    "AgentKnowledgeBinding",
    "AgentKnowledgeConfig",
    "AgentKnowledgeManifest",
    "AgentKnowledgeRelease",
    "AgentKnowledgeResource",
    "AgentSearchResponse",
    "AnswerResponse",
    "Backlink",
    "BacklinkList",
    "Citation",
    "DocumentDetail",
    "DocumentList",
    "DocumentRevision",
    "DocumentText",
    "DocumentWrite",
    "EvidenceConflict",
    "ExecutionPin",
    "FolderNode",
    "KnowledgeBase",
    "KnowledgeBaseDetail",
    "KnowledgeBaseHealth",
    "KnowledgeBaseRecord",
    "KnowledgeBaseStats",
    "KnowledgeCollection",
    "KnowledgeCollectionsResource",
    "KnowledgeDiff",
    "KnowledgeDocument",
    "KnowledgeDocumentsResource",
    "KnowledgeJob",
    "KnowledgeJobsResource",
    "KnowledgeRefs",
    "KnowledgeResource",
    "KnowledgeRetrievalsResource",
    "KnowledgeSection",
    "KnowledgeVersion",
    "KnowledgeVersionsResource",
    "Publication",
    "PublicationEvent",
    "QueryResponse",
    "RetrievalEvent",
    "RetrievalInfo",
    "RetrievalSnapshot",
    "RevisionList",
    "RiskAssessment",
    "SearchResponse",
    "SearchResult",
    "SectionDetail",
    "SectionMatch",
    "SectionTree",
    "Unset",
    "VersionDecision",
    "VersionDetail",
    "VersionLike",
    "VersionSelector",
    "VersionVerification",
    "VersionWrite",
    "knowledge_tool",
    "normalize_version",
    "version_number",
]

_LAZY = frozenset({"KnowledgeQuery", "KnowledgeRetriever", "KnowledgeTool"})


def __getattr__(name: str) -> Any:
    if name in _LAZY:
        return getattr(import_module("agenomic.knowledge._langchain"), name)
    raise AttributeError(f"module 'agenomic.knowledge' has no attribute {name!r}")
